apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    [{“kube.local”: [“10.178.11.220”]},
    {“kubelocal.com”: [“10.178.11.220”]}]
  upstreamNameservers: |
    [“10.178.11.220”]

