apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs
  nfs:
    # FIXME: use the right IP
    server: 10.178.11.188
    path: "/mnt/nfs/nfs/kubernetes/"

