apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: provisioner-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: provisioner
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: kube-system
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v1
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.178.11.188
            - name: NFS_PATH
              value: /mnt/nfs/nfs/kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.178.11.188
            path: /mnt/nfs/nfs/kubernetes
