apiVersion: v1
kind: Service
metadata:
  name: graphite
spec:
  selector:
    app: graphite
  ports:
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
   - port: 2003
     targetPort: 2003
     name: incoming
     protocol: TCP
   - port: 2004
     targetPort: 2004
     name: incoming-pickle
     protocol: TCP
   - port: 7002
     targetPort: 7002
     name: query
     protocol: TCP            
