apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-http
  namespace: default
spec:
  rules:
  - host: gitlab.kube.com
    http:
      paths:
      -  backend:
          serviceName: gitlab-gitlab-ce
          servicePort: http
